### ISSUE TITLE
how to fetch credential using php script?

### ISSUE THREAD

**Issue by vivekpanchall** [mittwald/vaultPHP#13]
this is my service class file, how to integrate this package using php 

<?php

namespace App\Services;

use VaultPHP\VaultClient;
use GuzzleHttp\Client;
use VaultPHP\Authentication\Provider\Token;
use VaultPHP\Exceptions\VaultException;
use VaultPHP\Exceptions\VaultResponseException;
use VaultPHP\SecretEngines\Engines\Transit\Transit;
use VaultPHP\Authentication\TokenAuthentication;

class VaultService
{
    protected $client;

    public function __construct()
    {
        $this->initializeClient();
    }

    protected function initializeClient()
    {
        $vaultAddr = "adress";
        $vaultToken = "token";

        $httpClient = new Client();
        $auth = new Token($vaultToken);

        // creating the vault request client
        $this->client = new VaultClient(
            $httpClient,
            $auth,
            $vaultAddr
        );
    }

    public function credentials()
    {
        try {
            $transit = new Transit($this->client);
            $response = $transit->listKeys();

            // Process the response
            $keys = $response->getKeys();
            var_dump($keys);

        } catch (\VaultPHP\Exceptions\VaultException $e) {
            echo "Vault Exception: " . $e->getMessage();exit;
            echo "Exception: " . $e->getMessage(); exit;
        }
    }
}

**Comment by ins0** [comment]
hello @vivekpanchall - please give more information were our code won't work as expected or throws an error. Please keep in mind that we can't assist on how to implement this repository in your codebase directly - if you need some examples - please look at the `Examples` Folder https://github.com/mittwald/vaultPHP/tree/master/examples.

**Comment by ins0** [comment]
Close - feel free to open it again.
